### PR TITLE
WIP:Added Order Tests

### PR DESCRIPTION
**Pull request by L4B0MB4**
I added ordering test. If you got time, please review the changes and feel free to request changes.

I added chai because I think the syntax is very intuitive. But please let me know if you dont think so.

### CODE REVIEW

**Comment by N3ol4N** [comment]
adding tests for sorting by specific elements is a great idea. the tests you wrote seem good imho, but at this point in time i cant do a full review, due to another project im involved in right now.
including chai is very good. we were thinking about that already. so thank you for that!
right now im unsure why the tests seems to fail.
Travis says "chromiumdrivers failed to load in time". i asume you are working on that already, so plz feel free to contact me when you found a solution. i will try to make room for that as soon as it seem stable!

**Comment by L4B0MB4** [comment]
@N3ol4N can you check if the tests run on your mac? On windows they are running fine O.o

**Comment by N3ol4N** [comment]
just checked your branch locally. same issue as with travis:
1) Application launch
       "before each" hook for "shows an initial window":
     Error: ChromeDriver did not start within 5000ms

but i tried the tests of the current master as well. same problem now.
i'm not quite sure, but i think the master passed its tests on the last merge. it seems odd that it's crashing now. maybe something outside of our codespace changed? versioning or something of chromium that's used?

**Comment by L4B0MB4** [comment]
That's really weird. I will create a virtual machine and try to find the misconfiguration

**Comment by L4B0MB4** [comment]
Good news :tada: the tests are running again! Still failing because my tests are wrong buuuuut they get executed

**Comment by N3ol4N** [comment]
These are very good news :-D
Thank you very much for your help! Could you share some of your insight about that problem? Did you find the reason for the changed behaviour?

**Comment by L4B0MB4** [comment]
The issue seem to be the very old versions of electron and related dependencies (see commit: e0a5f9f updating dependencies helped in circleci). Electron for example was about 5 major versions behind the current. Why the master / old tests were working - I have no idea.

**Comment by N3ol4N** [comment]
first of all thanks again for the fast help on the travis ci and the hotfix!
On future fixes we should use different branches to maintain the seperation of concerns in our project, but since we worked this out in direct contact and we have a stable version afterwards it should be fine this time :-)

This pull request will adress the issues #61, as well as it will add tests for sorting the table and it will fix an issue in the current master, where the repo was not opened in a correct way

**Pull request merged**
